apiVersion: v1
kind: Service
metadata:
    name: "bdoexdevcluster03-8d59"
    labels:
        app: "bdoexdevcluster03-8d59"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "bdoexdevcluster03-8d59"